name: allele_conditional
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - argon2-cffi=20.1.0
  - asttokens=2.0.5
  - attrs=21.4.0
  - backcall=0.2.0
  - beautifulsoup4
  - biopython
  - blas=1.0
  - bleach=4.1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.9.24
  - certifi=2022.5.18.1
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - colorama=0.4.4
  - cryptography=36.0.0
  - cudatoolkit=11.3.1
  - cycler=0.11.0
  - dbus=1.13.6
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.2.10
  - ffmpeg=4.3
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=3.3
  - intel-openmp=2021.4.0
  - ipykernel=6.9.1
  - ipython=8.3.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.1
  - jinja2=3.0.3
  - joblib=1.1.0
  - jsonschema=4.4.0
  - jupyter=1.0.0
  - jupyter_client=7.2.2
  - jupyter_console=6.4.3
  - jupyter_core=4.10.0
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.3.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=9.3.0
  - libiconv=1.15
  - libidn2=2.3.2
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuuid=1.0.3
  - libuv=1.40.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxml2=2.9.12
  - libzlib=1.2.11
  - llvmlite=0.38.0
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - nbclient=0.5.13
  - nbconvert=6.4.4
  - nbformat=5.3.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - nettle=3.7.3
  - notebook=6.4.11
  - numba=0.55.1
  - numpy=1.21.2
  - numpy-base=1.21.2
  - openh264=2.1.1
  - openssl=1.1.1q
  - packaging=21.3
  - pandas=1.2.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - patsy=0.5.2
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.0.1
  - pip=21.2.4
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py3dmol=1.8.1
  - pycparser=2.21
  - pygments=2.11.2
  - pynndescent=0.5.7
  - pyopenssl=22.0.0
  - pyparsing=3.0.7
  - pyqt=5.9.2
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.11
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.1
  - python_abi=3.9
  - pytorch=1.11.0
  - pytorch-mutex=1.0=cuda
  - pytz=2022.1
  - pyzmq=22.3.0
  - qt=5.9.7
  - qtconsole=5.3.0
  - qtpy=2.0.1
  - readline=8.1.2
  - requests=2.27.1
  - scikit-learn=0.23.2
  - scipy=1.5.3
  - seaborn=0.11.2
  - seaborn-base=0.11.2
  - send2trash=1.8.0
  - sip=4.19.13
  - six=1.16.0
  - soupsieve=2.3.1
  - sqlite=3.38.0
  - stack_data=0.2.0
  - statsmodels=0.13.2
  - tbb=2021.5.0
  - terminado=0.13.1
  - testpath=0.5.0
  - threadpoolctl=3.1.0
  - tk=8.6.11
  - torchaudio=0.11.0
  - torchvision=0.12.0
  - tornado=6.1
  - traitlets=5.1.1
  - typing_extensions=4.1.1
  - tzdata=2021e
  - umap-learn=0.5.3
  - urllib3=1.26.8
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - zeromq=4.3.4
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - absl-py==1.0.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - antlr4-python3-runtime==4.9.3
    - async-timeout==4.0.2
    - av==9.2.0
    - bayesian-optimization==1.2.0
    - biotite==0.33.0
    - boto3==1.24.17
    - botocore==1.27.17
    - cachetools==5.0.0
    - click==8.0.4
    - cloudpickle==2.1.0
    - contextlib2==21.6.0
    - dill==0.3.5.1
    - distlib==0.3.4
    - dm-tree==0.1.7
    - einops==0.6.0
    - fair-esm==2.0.0
    - filelock==3.6.0
    - frozenlist==1.3.0
    - fsspec==2022.2.0
    - future==0.18.2
    - gdown==4.4.0
    - google-auth==2.6.2
    - google-auth-oauthlib==0.4.6
    - grpcio==1.43.0
    - gym==0.21.0
    - hub==2.5.2
    - huggingface-hub==0.4.0
    - humbug==0.2.7
    - hyperopt==0.2.7
    - imageio==2.19.5
    - importlib-metadata==4.11.3
    - jmespath==1.0.1
    - lmdb==1.3.0
    - lz4==4.0.1
    - markdown==3.3.6
    - ml-collections==0.1.1
    - msgpack==1.0.4
    - multidict==6.0.2
    - multiprocess==0.70.13
    - networkx==2.8.4
    - numcodecs==0.10.0
    - oauthlib==3.2.0
    - pytorch-lightning==1.5.10
    - tensorboard==2.8.0
    - tape-proteins==0.5    
    - tokenizers==0.11.6
    - torchmetrics==0.7.3
    - tqdm==4.63.1
    - transformers==4.17.0
